commands:
  Опустить:
    1: 0   # Плечо вниз
    2: 0   # Локоть вниз

  Вниз:
    2: 0

  Открыть:
    3: 180  # Захват полностью открыт

  Вверх:
    2: 180

  Захватить:
    3: 0  # Захват закрыт

  Влево:
    0: 180  # Основание поворот влево

  Поднять:
    1: 180
    2: 180

  Закрыть:
    3: 0

  Домой:
    0: 90
    1: 0
    2: 0
    3: 0

  Вправо:
    0: 0
