commands:
  Домой:
    0: 90   # Основание центр
    1: 90   # Плечо в среднее положение
    2: 90   # Локоть в среднее положение
    3: 90   # Захват в полураскрытом положении

  Захватить:
    3: 0       # Захват закрыть

  Открыть:
    3: 180     # Захват открыть

  Закрыть:
    3: 0       # Синоним Захватить

  Поднять:
    1: 45      # Плечо вверх
    2: 135     # Локоть вверх

  Опустить:
    1: 135     # Плечо вниз
    2: 45      # Локоть вниз

  Вверх:
    1: 45      # Только плечо вверх

  Вниз:
    1: 135     # Только плечо вниз

  Влево:
    0: 180     # Основание влево до конца

  Вправо:
    0: 0       # Основание вправо до конца

  Найти:        # Движение "поиск объекта" (медленное движение слева направо)
    0: 0
    1: 90
    2: 90
    3: 180

  Двигаться:    # Небольшое плавное движение вперёд (локоть)
    2: 120

  Сменить:      # Меняет текущее положение на противоположное
    0: 180
    1: 180
    2: 180
    3: 90

  Остановиться: # Вернуться в нейтральную позицию
    0: 90
    1: 90
    2: 90
    3: 90
