# Общие настройки аудио
common:
  sample_rate: 16000
  debug: True
  desired_length: 96000

# Настройки для извлечения признаков для распознавания команд
command_features:
  n_fft: 480
  hop_length: 160
  win_length: 480
  n_mels: 64
  n_mfcc: 32
  window: "hann"
  normalize: True
  center: True
  power: 2.0
  n_mels: 64
  fmin: 0.0
  fmax: 8000.0
  htk: True

# Настройки для VAD
vad_features:
  merge_segments: True
  merge_gap: 0.5 # в секундах
  min_signal_lenght: 1000

# Настройки кольцевого буфера
ring_buffer:
  duration: 6  # длительность буфера в секундах
  update_interval: 1  # интервал обновления в секундах
  use_ring_buffer: False  # использовать кольцевой буфер вместо обычной записи
