Architecture:
  CNN_params:
    in_channels: 1
    out_channels: &CNN_out_channels !!int 32
    kernel_size: 3
    stride: 2
    padding: 1
  ResCNN_params:
    in_channels: *CNN_out_channels # = CNN_out_channels
    out_channels: *CNN_out_channels
    kernel_size: 3
    stride: 1
    dropout: 0.1
    n_feats: 32
    padding: 1
    n_cnn_layers: 3
  Fully_connected_params:
    in_features: 2048 # n_feats * out_channels
    out_features: &FC_out_features !!int 512
  RNN_params:
    input_size: *FC_out_features
    hidden_size: &RNN_hidden_size !!int 512 
    num_layers: 5
    bidirectional: True
    dropout: 0.1
    rnn_type: 'lstm'
  Attention_params:
    feature_dim: *RNN_hidden_size # = RNN_hidden_size
    step_dim: 10
  Classifier_params:
    in_features: *FC_out_features # = RNN_input_size
    out_features: 256
    dropout: 0.1
    n_class: 18 # num_commands

Settings: 
  Optimizer_Scheduler:
    lr_rate: 5e-4
    weight_decay: 0.0005
    amsgrad: True
    max_lr: 0.05
    div_factor: 250
    max_norm: 1
  Other:
    epochs: 10
    batch_size: 128
