models:
  vad: "/Users/litvan007/Voice-commands-recognition/models/conv_emobase.onnx"
  command_recognizer: "/home/i.litvinov/Voice-commands-recognition/models/model.onnx"
  command_recognizer_large: "models/command_recognizer_large.onnx"
