architecture:
  CNN_params:
    in_channels: 1
    out_channels: 32
    kernel_size: 3
    stride: 2
    padding: 1
  Fully_connected_params:
    in_features: 64
    out_features: 512
  ResCNN_params:
    in_channels: 32 # = CNN_out_channels
    out_channels: 32
    kernel_size: 3
    stride: 1
    dropout: 0.1
    n_feats: 128 
    padding: 1
    n_cnn_layers: 3
  RNN_params:
    input_size: 512
    hidden_size: 512 
    num_layers: 5
    bidirectional: True
    dropout: 0.1
    rnn_type: 'lstm'
  Attention_params:
    feature_dim: 512 # = RNN_hidden_size
    step_dim: 10
  Classifier_params:
    in_features: 512 # = RNN_input_size
    out_features: 256
    dropout: 0.1
    n_class: 18 # num_commands

Settings: 
  Optimizer_Scheduler:
    lr_rate: 5e-4
    weight_decay: 0.0005
    amsgrad: True
    max_lr: 0.05
    div_factor: 250
    max_norm: 1
  Other:
    epochs: 10
    batch_size: 128
