labels_map:
  0: "Опустить"
  1: "Двигаться"
  2: "Сохранить"
  3: "Вниз"
  4: "Старт"
  5: "Открыть"
  6: "Сменить"
  7: "Вверх"
  8: "Захватить"
  9: "Влево"
  10: "Поднять"
  11: "Закрыть"
  12: "Остановиться"
  13: "Загрузить"
  14: "Найти"
  15: "Стоп"
  16: "Домой"
  17: "Вправо"

confidence_thresholds:
  default: 0.6
  overrides:
    4: 0.7   # Старт
    9: 0.28
    15: 0.7  # Стоп
    12: 0.7  # Остановиться
    16: 0.3
